env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  indent:
    - error
    - tab
  quotes:
    - error
    - double
  semi:
    - error
    - always
  max-len:
    - error
    - {code: 100, ignoreUrls: true, ignoreComments: true}
  no-multiple-empty-lines:
    - error
    - {max: 1, maxEOF: 0, maxBOF: 0}